### PR TITLE
Test change.

### PR DESCRIPTION
**Pull request by mattmoor**

### CODE REVIEW

**Comment by mattmoor** [comment]
test this

**Comment by stevekuznetsov** [comment]
test comment

**Comment by mattmoor** [comment]
test comment

**Comment by mattmoor** [comment]
Testing remote secret

**Comment by mattmoor** [comment]
test comment

**Comment by mattmoor** [comment]
test comment with newline, from my machine

**Comment by mattmoor** [comment]
Testing remote secret, with newline

**Comment by mattmoor** [comment]
@mattmoor: What do I look like? A JOKE MACHINE!?

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-332991107):

>/joke


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor** [comment]
@BenTheElder: Archaeology really is a career in ruins.

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-332992333):

>/joke


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor** [comment]
@mattmoor: My dog used to chase people on a bike a lot. It got so bad I had to take his bike away.

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-332999183):

>/joke


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor** [comment]
@mattmoor: What is the hardest part about sky diving? The ground.

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-333154073):

>/joke


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor** [comment]
test this

**Comment by 0xmichalis** [comment]
You are going to stumble upon issues if you use the same account as a bot and for running bot commands. There are commands where the bot comments are ignored (we may do this in all of them).

**Comment by mattmoor** [comment]
@mattmoor: What do you call two barracuda fish?  A Pairacuda!

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-333283899):

>/joke


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor-sockpuppet** [comment]
@mattmoor: What do you call corn that joins the army? Kernel.

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-333320055):

>/joke


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor-sockpuppet** [comment]
@mattmoor: you can't request testing unless you are a [mattmoor](https://github.com/orgs/mattmoor/people) member.

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-333320233):

>/test this


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mattmoor** [comment]
@kargakis thanks!

**Comment by mattmoor-sockpuppet** [comment]
@mattmoor: you can't request testing unless you are a [mattmoor](https://github.com/orgs/mattmoor/people) member.

<details>

In response to [this](https://github.com/mattmoor/rules_docker/pull/1#issuecomment-333320376):

>/test this


Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request closed without merging**
